# This rule is not used by the project oauth-proxy-op itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to oauth.anshulg.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oauth-proxy-op
    app.kubernetes.io/managed-by: kustomize
  name: proxy-viewer-role
rules:
- apiGroups:
  - oauth.anshulg.com
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oauth.anshulg.com
  resources:
  - proxies/status
  verbs:
  - get
